# Generated by Django 2.1 on 2018-08-17 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcases', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.BigIntegerField(blank=True, default=0)),
                ('done', models.BooleanField(blank=True, default=False)),
                ('subdate', models.DateTimeField(auto_now_add=True)),
                ('lang', models.CharField(max_length=200)),
                ('code', models.TextField()),
                ('customin', models.TextField(blank=True, default=None)),
                ('errors', models.TextField(blank=True, default=None)),
                ('testresults', models.TextField(blank=True, default=None)),
                ('q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.question')),
            ],
        ),
    ]
